package com.atharvaj77.drugchain;

import com.smartcontract.drugchain.DrugchainContract;
import org.springframework.stereotype.Service;
import org.web3j.crypto.Credentials;
import org.web3j.crypto.RawTransaction;
import org.web3j.crypto.TransactionEncoder;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.DefaultBlockParameterName;
import org.web3j.protocol.core.methods.response.EthGetTransactionCount;
import org.web3j.protocol.core.methods.response.EthSendTransaction;
import org.web3j.protocol.http.HttpService;
import org.web3j.utils.Numeric;

import java.io.IOException;
import java.math.BigInteger;
import java.util.List;

@Service
public class BlockchainService {

    private final Web3j web3j;
    private final Credentials credentials;
    private final DrugchainContract contract;
    private final String contractAddress = "0x420DB4a10306Ae8E7bE6ce7A00074f43fb2EFcfE"; // Replace `YourContract` with the actual contract wrapper generated by Web3j

    public BlockchainService() {
        String ganacheUrl = "HTTP://127.0.0.1:7545";
        web3j = Web3j.build(new HttpService(ganacheUrl));
        credentials = Credentials.create("0x76ef7d36bd8644b3f1662c779a5bfb1cd5fee9b3b09bbd6ed258ba8c1a2e360f"); // Replace `YOUR_PRIVATE_KEY` with your actual private key

        contract = DrugchainContract.load(
                "0x420DB4a10306Ae8E7bE6ce7A00074f43fb2EFcfE",
                web3j,
                credentials,
                BigInteger.valueOf(1000000),
                BigInteger.valueOf(3000000)
        );
    }

    public String createProduct(String itemName, String mfgDate, String expiryDate,
                                String batchNo, BigInteger numberUnits, String history,
                                String fromAdd, String toAdd) throws IOException {
        BigInteger nonce = getNonce(fromAdd);

        RawTransaction rawTransaction = RawTransaction.createTransaction(
                nonce,
                BigInteger.valueOf(1000000),
                BigInteger.valueOf(3000000),
                contractAddress,
                contract.createProduct(
                        itemName,
                        mfgDate,
                        expiryDate,
                        batchNo,
                        numberUnits,
                        history,
                        BigInteger.valueOf(-1),
                        fromAdd,
                        toAdd
                ).encodeFunctionCall()
        );

        byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
        String hexValue = Numeric.toHexString(signedMessage);

        EthSendTransaction ethSendTransaction = web3j.ethSendRawTransaction(hexValue).send();
        return ethSendTransaction.getTransactionHash();
    }

    public void updateHistory(BigInteger pid, String hist, String addFrom) throws IOException {
        BigInteger nonce = getNonce(addFrom).add(BigInteger.ONE);

        RawTransaction rawTransaction = RawTransaction.createTransaction(
                nonce,
                BigInteger.valueOf(1000000),
                BigInteger.valueOf(3000000),
                contractAddress,
                contract.updateHistory(pid, hist).encodeFunctionCall()
        );

        byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
        String hexValue = Numeric.toHexString(signedMessage);

        web3j.ethSendRawTransaction(hexValue).send();
    }

    // Other functions and methods omitted for brevity

    public List getAllProducts(String pid) throws Exception {
        return contract.findProduct(pid).send();
    }

    public DrugchainContract.Product getProduct(BigInteger productId) throws Exception {
        return contract.getProductDetails(productId).send();
    }

    public BigInteger getLastProductId(String address) throws Exception {
        return contract.getLastProductId(address).send();
    }

    private BigInteger getNonce(String address) throws IOException {
        EthGetTransactionCount transactionCount = web3j.ethGetTransactionCount(
                address,
                DefaultBlockParameterName.LATEST
        ).send();

        return transactionCount.getTransactionCount();
    }
}
